version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0
  node: circleci/node@4.1

executors:
  node:
    docker:
      - image: cimg/node:15.1

jobs:
  build-and-test:
    executor: node
    steps:
      - checkout
      - aws-cli/setup
      - run: npm run registry-login
      - node/install-packages
      - run: npm run check

  publish:
    executor: node
    steps:
      - checkout
      - aws-cli/setup
      - run: npm run registry-login
      - node/install-packages
      - run: npm run build
      - run: npm publish

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          context:
            - dynamo
            - aws
          filters:
            branches:
              ignore: main
      - publish:
          context:
            - aws
