version: 2.1

orbs:
  node: circleci/node@4.1

executors:
  node:
    docker:
      - image: cimg/node:15.1

jobs:
  build-and-test:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run: npm lint
      - run: npm test

workflows:
  sample:
    jobs:
      - build-and-test
