version: 2.1

orbs:
  node: circleci/node@4.1

executors:
  node:
    docker:
      - image: cimg/node:15.1

jobs:
  build-and-test:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run: npm run check

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          context:
            - dynamo
          filters:
            branches:
              ignore: main
